const COMPLIMENTS = [
  'Nice work!',
  'Stupendous!',
  'You rock!',
  'Keep it up!',
  'Never give up!',
  '👍👍👍',
  '⭐⭐⭐',
  'Congrats, Wordler!',
  'You are a star!',
  'Well done!',
  'Great job!',
  'Fantastic!',
  'Amazing effort!',
  'You crushed it!',
  'Legendary!',
  'Superb!',
  'Bravo!',
  'You’re unstoppable!',
  'So impressive!',
  'Outstanding!',
  'You nailed it!',
  'Keep shining!',
  '💪💪💪',
  'Way to go!',
  'Incredible!',
  'Pure genius!',
  'On fire!',
  '🙌🙌🙌',
  '👏👏👏',
  'Elite Wordling!'
];

export default COMPLIMENTS;