const COMPLIMENTS = [
  'Nice work!',
  'Stupendous!',
  'You rock!',
  'Keep it up!',
  'Never give up!',
  '\u{1F44D}\u{1F44D}\u{1F44D}',
  '\u2B50\u2B50\u2B50',
  'Congrats, Wordler!',
  'You are a star!',
  'Well done!',
  'Great job!',
  'Fantastic!',
  'Amazing effort!',
  'You crushed it!',
  'Legendary!',
  'Superb!',
  'Bravo!',
  'You\u2019re unstoppable!',
  'So impressive!',
  'Outstanding!',
  'You nailed it!',
  'Keep shining!',
  '\u{1F4AA}\u{1F4AA}\u{1F4AA}',
  'Way to go!',
  'Incredible!',
  'Pure genius!',
  'On fire!',
  '\u{1F64C}\u{1F64C}\u{1F64C}',
  '\u{1F44F}\u{1F44F}\u{1F44F}',
  'Elite Wordling!'
];

export default COMPLIMENTS;
